version: '3.8'
services:
  db:
    image: postgres:15
    container_name: gorupg
    environment:
      POSTGRES_USER: goru
      POSTGRES_PASSWORD: goru
      POSTGRES_DB: goru_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: gorubackend
    environment:
      - DATABASE_URL=postgresql://goru:goru@db:5432/goru_db
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

volumes:
  pgdata: 