"""update users table

Revision ID: 44d93914ab04
Revises: 8fbe1b4edcff
Create Date: 2025-07-24 01:10:51.866151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44d93914ab04'
down_revision = '8fbe1b4edcff'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_name', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('amount', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('orders', 'order_date')
    op.drop_column('orders', 'total_amount')
    op.drop_column('orders', 'status')
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'username')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_active', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'name')
    op.add_column('orders', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('order_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'created_at')
    op.drop_column('orders', 'amount')
    op.drop_column('orders', 'product_name')
    # ### end Alembic commands ###