"""sync models

Revision ID: ee5c59f054df
Revises: f5ee6407b6f1
Create Date: 2025-07-24 20:44:41.758879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee5c59f054df'
down_revision = 'f5ee6407b6f1'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###