"""add_unit_price_and_supplier_to_stocks

Revision ID: ff6fedb38d28
Revises: ee5c59f054df
Create Date: 2025-07-30 23:30:30.649640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff6fedb38d28'
down_revision = 'ee5c59f054df'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Önce nullable olarak ekle
    op.add_column('stocks', sa.Column('unit_price', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('supplier', sa.String(), nullable=True))

    # Mevcut kayıtlara default değer ata
    op.execute("UPDATE stocks SET unit_price = 0.0 WHERE unit_price IS NULL")

    # Sonra NOT NULL yap
    op.alter_column('stocks', 'unit_price', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'supplier')
    op.drop_column('stocks', 'unit_price')
    # ### end Alembic commands ###