name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort ruff

      - name: Run Black (formatting check)
        run: black --check backend/app/

      - name: Run isort (import sorting check)
        run: isort --check-only --profile black backend/app/

      - name: Run Ruff (fast linting)
        run: ruff check backend/app/ --ignore E501,F401,F841,E722,E712,F821

  build-test:
    runs-on: ubuntu-latest
    needs: lint-and-format
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: goru
          POSTGRES_PASSWORD: goru
          POSTGRES_DB: goru_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U goru"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python (for coverage upload)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Docker image build
        run: |
          docker build -t goru-backend-test:ci -f backend/Dockerfile backend

      - name: Run basic tests
        env:
          DATABASE_URL: postgresql://goru:goru@localhost:5432/goru_db
          ENVIRONMENT: test
        run: |
          docker run --rm --network host -e DATABASE_URL=${DATABASE_URL} -e ENVIRONMENT=${ENVIRONMENT} goru-backend-test:ci pytest /app/tests/test_users.py -v

      - name: Run auth tests
        env:
          DATABASE_URL: postgresql://goru:goru@localhost:5432/goru_db
          ENVIRONMENT: test
        run: |
          docker run --rm --network host -e DATABASE_URL=${DATABASE_URL} -e ENVIRONMENT=${ENVIRONMENT} goru-backend-test:ci pytest /app/tests/test_auth_error_handling.py -v

      - name: Run mock tests
        env:
          DATABASE_URL: postgresql://goru:goru@localhost:5432/goru_db
          USE_MOCK: true
          ENVIRONMENT: test
        run: |
          docker run --rm --network host -e DATABASE_URL=${DATABASE_URL} -e USE_MOCK=${USE_MOCK} -e ENVIRONMENT=${ENVIRONMENT} goru-backend-test:ci pytest /app/tests/test_mock_endpoints.py -v

      - name: Upload coverage to Codecov (optional)
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
        continue-on-error: true

  mock-tests:
    runs-on: ubuntu-latest
    needs: lint-and-format
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker image build
        run: |
          docker build -t goru-backend-mock:ci -f backend/Dockerfile backend

      - name: Run mock tests
        env:
          USE_MOCK: true
        run: |
          docker run --rm -e USE_MOCK=${USE_MOCK} goru-backend-mock:ci pytest /app/tests/test_mock_endpoints.py -v