name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort ruff

      - name: Run Black (formatting check)
        run: black --check backend/app/

      - name: Run isort (import sorting check)
        run: isort --check-only --profile black backend/app/

      - name: Run Ruff (fast linting)
        run: ruff check backend/app/ --ignore E501,F401,F841,E722,E712,F821

  build-test:
    runs-on: ubuntu-latest
    needs: lint-and-format

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python (for coverage upload)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Docker image build
        run: |
          docker build -t goru-backend-test:ci -f backend/Dockerfile backend

      - name: Run mock tests
        env:
          USE_MOCK: true
          ENVIRONMENT: test
          TESTING: true
        run: |
          docker run --rm -e USE_MOCK=${USE_MOCK} -e ENVIRONMENT=${ENVIRONMENT} -e TESTING=${TESTING} goru-backend-test:ci pytest app/tests/test_mock_endpoints.py -v

      - name: Upload coverage to Codecov (optional)
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
        continue-on-error: true

  mock-tests:
    runs-on: ubuntu-latest
    needs: lint-and-format
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker image build
        run: |
          docker build -t goru-backend-mock:ci -f backend/Dockerfile backend

      - name: Run mock tests
        env:
          USE_MOCK: true
          TESTING: true
        run: |
          docker run --rm -e USE_MOCK=${USE_MOCK} -e TESTING=${TESTING} goru-backend-mock:ci pytest app/tests/test_mock_endpoints.py -v