name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu checkout et
        uses: actions/checkout@v4

      - name: Docker image build (local)
        run: |
          docker build -t goru-backend-test:ci -f backend/Dockerfile .

      - name: Docker container içinde testleri çalıştır
        run: |
          docker run --rm goru-backend-test:ci pytest --cov=app --cov-report=xml