name: Import Coverage Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  import-coverage:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install pytest pytest-cov
        
    - name: Run Import Coverage Tests
      working-directory: ./backend
      run: |
        echo "🔍 Running Import Coverage Tests..."
        python -m pytest app/tests/test_import_coverage.py -v --tb=short
        
    - name: Run Full Test Suite
      working-directory: ./backend
      run: |
        echo "🧪 Running Full Test Suite..."
        python -m pytest app/tests/ -v --tb=short --cov=app --cov-report=term-missing
        
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage.xml
        flags: import-coverage
        name: import-coverage-${{ matrix.python-version }}
        
    - name: Comment PR with results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const testOutput = fs.readFileSync('${{ github.workspace }}/backend/test-results.txt', 'utf8');
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## Import Coverage Test Results ✅
            
            **Python Version:** ${{ matrix.python-version }}
            
            **Status:** All imports successful (100% coverage)
            
            **Test Output:**
            \`\`\`
            ${testOutput}
            \`\`\`
            
            ✅ **Import Coverage:** 35/35 modules imported successfully
            ✅ **Critical Modules:** All critical modules import correctly
            ✅ **Route Modules:** All route modules import correctly
            ✅ **Middleware Modules:** All middleware modules import correctly
            ✅ **Utility Modules:** All utility modules import correctly
            ✅ **Script Modules:** All script modules import correctly` 